In [1]:
import numpy as np

In [4]:
ar = np.array([1,2,5])
ar = np.array((1,2,3))

In [10]:
#Multidimentional array
arr_multi = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [7]:
print(arr.ndim)

3


In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

<h4>
Checking the dimension of an Array
</h4>

In [9]:
arr.ndim

5

<h2>Indexing</h2>

In [13]:
# indexing for multidimentional array
arr_multi[0,1,2]

6

<h2>Slicing</h2>

Regurlar conventions: [start:end:step]

In [14]:
# Sllicing for multidimentional array

In [15]:
arr_multi[0:1,0:2]

array([[[1, 2, 3],
        [4, 5, 6]]])

<h2>Data types in Numpy</h2>

<pre>i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )</pre>

<h4>Checking the Data Type of an Array
</h4>

In [17]:
print(arr.dtype)

int64


<h4>Creating Arrays With a Defined Data Type
</h4>

In [19]:
arr = np.array([1, 2, 3, 4], dtype='S')

<h4>Converting Data Type on Existing Arrays
</h4>

In [20]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

<h2>NumPy Array Copy vs View</h2>

In [21]:
x = arr.copy()
x = arr.view()

<b>The copy SHOULD NOT be affected by the changes made to the original array</b>

<b>The view SHOULD be affected by the changes made to the original array.
</b>

<h4>Check if Array Owns it's Data</h4>

In [23]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1.1 2.1 3.1]


<h2>NumPy Array Copy vs View</h2>

In [24]:
arr.shape

(3,)

In [26]:
arr_multi.shape

(2, 2, 3)

<h2>NumPy Array Reshaping</h2>

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

<pre>
Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

</pre>

<h4>
Unknown Dimension
</h4>

<pre>
Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.
</pre>

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

<b>Note: We can not pass -1 to more than one dimension.</b>

<h2>NumPy Array Iterating</h2>

<h4>Iterating Arrays Using nditer()</h4>

In [32]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [33]:
for x in np.nditer(arr[:, ::2]):
  print(x)

1
2
5
6


<h4>Enumerated Iteration Using ndenumerate()</h4>

In [35]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


<h2>NumPy Joining Array</h2>

In [38]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


<b>Default axis is 0</b>

<h3>Stacking</h3>

In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [44]:
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [45]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [47]:
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


<h4>If axis for stack function is 0 then it works like vstack</h4>
<h4>If axis for stack function is 1 then it works like hstack</h4>

<h2>Splitting NumPy Arrays</h2>

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


<h2>Search Numpy Array</h2>

In [59]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


<h4>Which means that the value 4 is present at index 3, 5, and 6.</h4>

<b>There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
</b>

In [61]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)


1


In [62]:
# Search from right side
x = np.searchsorted(arr, 7, side='right')

In [63]:
np.sort(arr)

array([6, 7, 8, 9])

<b>Sort mehod returns a new array</b>

<h2>Filtering Arrays
</h2>

In [64]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [65]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
